const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const pages=$$('.page'),nav=$$('#nav button');function go(id){pages.forEach(x=>x.classList.toggle('active',x.id===id));nav.forEach(x=>x.classList.toggle('active',x.dataset.page===id));localStorage.setItem('cs_page',id);scrollTo({top:0,behavior:'smooth'});if(id==='resultado')renderResult()}nav.forEach(x=>x.onclick=()=>go(x.dataset.page));$$('[data-go]').forEach(x=>x.onclick=()=>go(x.dataset.go));

$('#theme').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem('cs_dark',document.body.classList.contains('dark'));$('#theme').textContent=document.body.classList.contains('dark')?'☀️':'🌙'};if(localStorage.getItem('cs_dark')==='true'){document.body.classList.add('dark');$('#theme').textContent='☀️'}

let locationState={ok:false,lat:null,lon:null};$('#locBtn').onclick=()=>{if(!navigator.geolocation){$('#locText').textContent='Este navegador no permite geolocalización.';return}$('#locText').textContent='Solicitando permiso de ubicación…';navigator.geolocation.getCurrentPosition(p=>{locationState={ok:true,lat:p.coords.latitude,lon:p.coords.longitude};localStorage.setItem('cs_location',JSON.stringify(locationState));$('#locText').textContent='Ubicación obtenida. Casa Segura la usará para contextualizar tu evaluación.';$('#coords').textContent=`Coordenadas: ${p.coords.latitude.toFixed(5)}, ${p.coords.longitude.toFixed(5)}`},()=>{$('#locText').textContent='No se pudo obtener la ubicación. Puedes continuar sin ella.'})};
try{const l=JSON.parse(localStorage.getItem('cs_location'));if(l?.ok){locationState=l;$('#locText').textContent='Ubicación guardada en este dispositivo.';$('#coords').textContent=`Coordenadas: ${l.lat.toFixed(5)}, ${l.lon.toFixed(5)}`}}catch(e){}

const qdata=[
['Estructura visible','¿Observas grietas importantes, daños visibles o desprendimientos?'],['Estructura visible','¿La vivienda ha presentado daños después de un sismo o evento intenso?'],['Electricidad','¿Hay cables pelados, enchufes deteriorados o conexiones improvisadas?'],['Electricidad','¿Se sobrecargan tomacorrientes o extensiones?'],['Techo y drenaje','¿Hay filtraciones, humedad o manchas en techo/paredes?'],['Techo y drenaje','¿Las canaletas y drenajes se encuentran limpios y operativos?'],['Evacuación','¿Las salidas y pasillos están despejados?'],['Evacuación','¿Los muebles altos y objetos pesados están asegurados?'],['Incendio','¿La cocina y zonas de calor están libres de materiales inflamables?'],['Preparación','¿Tu familia sabe dónde reunirse y cómo comunicarse?']];
const qs=$('#questions');let answers=JSON.parse(localStorage.getItem('cs_answers')||'{}');qdata.forEach((q,i)=>{const d=document.createElement('article');d.className='question';d.innerHTML=`<h3>${q[0]}</h3><p>${q[1]}</p><div class="opts">${['Sí','No','No estoy seguro'].map(v=>`<button data-i="${i}" data-v="${v}">${v}</button>`).join('')}</div>`;qs.appendChild(d)});function paintAnswers(){$$('.opts button').forEach(b=>b.classList.toggle('selected',answers[b.dataset.i]===b.dataset.v))}$$('.opts button').forEach(b=>b.onclick=()=>{answers[b.dataset.i]=b.dataset.v;localStorage.setItem('cs_answers',JSON.stringify(answers));paintAnswers()});paintAnswers();

const bagItems=['Agua','Alimentos no perecibles','Linterna y pilas','Radio','Botiquín','Documentos importantes','Higiene','Ropa de abrigo'];let bagState=JSON.parse(localStorage.getItem('cs_bag')||'[]');$('#bag').innerHTML=bagItems.map((x,i)=>`<label><input type=checkbox data-bi="${i}" ${bagState[i]?'checked':''}> ${x}</label>`).join('');function bagUpdate(){bagState=$$('#bag input').map(x=>x.checked);localStorage.setItem('cs_bag',JSON.stringify(bagState));$('#bagScore').textContent=`${bagState.filter(Boolean).length}/${bagItems.length} preparados.`}$$('#bag input').forEach(x=>x.onchange=bagUpdate);bagUpdate();

const photoItems=['Fachada','Techo','Sala o zona común','Cocina','Escaleras','Instalación eléctrica','Daño visible'];let photos=JSON.parse(localStorage.getItem('cs_photos')||'{}');$('#photoGrid').innerHTML=photoItems.map((x,i)=>`<article class="photo-card"><div class="photo-preview" id="pv${i}">${photos[i]?'Foto guardada':'📷 Foto opcional'}</div><div class="inside"><b>${x}</b><p class="mini">Registra una condición visible.</p><label class="upload">Tomar / seleccionar foto<input type=file accept="image/*" capture="environment" data-p="${i}"></label></div></article>`).join('');$$('.photo-card input').forEach(inp=>inp.onchange=e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{photos[inp.dataset.p]=r.result;localStorage.setItem('cs_photos',JSON.stringify(photos));$('#pv'+inp.dataset.p).innerHTML=`<img src="${r.result}" alt="Registro de ${photoItems[inp.dataset.p]}">`};r.readAsDataURL(f)});Object.entries(photos).forEach(([i,v])=>$('#pv'+i).innerHTML=`<img src="${v}" alt="Foto guardada">`);

['meeting','contact','owner'].forEach(id=>{const el=$('#'+id);el.value=localStorage.getItem('cs_'+id)||'';el.oninput=()=>localStorage.setItem('cs_'+id,el.value)});$('#savePlan').onclick=()=>{$('#planMsg').textContent='Plan guardado en este dispositivo ✓'};

function scoreAnswers(){let total=0,n=qdata.length;for(let i=0;i<n;i++){const a=answers[i];total+=a==='Sí'?100:a==='No'?0:50}return Math.round(total/n)}
function riskScore(){let checked=$$('#hazards input:checked').length;let s=70-checked*7;if($('#safePlace').value==='No')s-=10;if($('#route').value==='No')s-=10;if(!locationState.ok)s-=5;return Math.max(0,Math.min(100,s))}
function level(p){return p>=80?['🟢','PREPARADA','green']:p>=50?['🟡','EN PREPARACIÓN','yellow']:['🔴','REQUIERE ATENCIÓN','red']}
function renderResult(){const a=scoreAnswers(),r=riskScore(),b=Math.round(bagState.filter(Boolean).length/bagItems.length*100),overall=Math.round(a*.45+r*.25+b*.30),lv=level(overall);$('#resultBox').innerHTML=`<div class="circle ${lv[2]}">${overall}%</div><h2>${lv[0]} ${lv[1]}</h2><div class="meter"><i style="width:${overall}%"></i></div><div class="grid two"><div class="metric">🏠 Vivienda <span>${a}%</span></div><div class="metric">📍 Entorno <span>${r}%</span></div><div class="metric">🎒 Preparación <span>${b}%</span></div><div class="metric">📸 Evidencias <span>${Object.keys(photos).length}/${photoItems.length}</span></div></div><p class="mini">El índice es orientativo y educativo. Una fotografía o cuestionario no puede confirmar la seguridad estructural de una vivienda.</p>`;let pri=[];if(a<80)pri.push(['🏠','Revisar condiciones de la vivienda','Prioriza los ítems respondidos como “No” o “No estoy seguro”.']);if(r<80)pri.push(['📍','Revisar riesgos del entorno','Identifica rutas y puntos seguros y consulta fuentes oficiales de tu localidad.']);if(b<80)pri.push(['🎒','Completar mochila de emergencia','Agrega los elementos que aún faltan.']);if(Object.keys(photos).length<3)pri.push(['📸','Completar registro visual','Toma fotos de las zonas que deseas documentar.']);$('#priorities').innerHTML=pri.slice(0,4).map(x=>`<article class="card priority"><h3>${x[0]} ${x[1]}</h3><p>${x[2]}</p></article>`).join('')||'<article class="card"><h3>✅ Mantén la prevención</h3><p>Continúa revisando periódicamente tu vivienda y actualiza tu plan familiar.</p></article>'}
$('#reset').onclick=()=>{if(confirm('¿Reiniciar toda la evaluación y borrar los datos guardados?')){['cs_answers','cs_bag','cs_photos','cs_meeting','cs_contact','cs_owner'].forEach(k=>localStorage.removeItem(k));location.reload()}};const init=localStorage.getItem('cs_page');if(init)go(init);
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js').catch(()=>{}));